### ISSUE TITLE
where is 1.6.1 source?

### ISSUE THREAD

**Issue by jdiercks** [berglundinst/NuEVI#42]
Hi, my NuRAD came preloaded with v1.6.1, and I have some ideas for enhancements that I want to try adding, but this repo is only at 1.6.0 and I don't want to lose the 1.6.1 changes. Can the repo get updated with latest code? Thanks.

--Jon

**Comment by jstck** [comment]
Due to diverging code (and the 1.6.1 part of it not being actually committed to git), we unfortunately don't have a "fixed point" in the source tree for what was built as the 1.6.1 release. I have made a release for it mostly just to have the firmware files and documentation for it.
I'll comb through and commit the changes in 1.6.1, and that together with some other fixes that have happened since then will be part of a later release shortly (presumably 1.6.2).

**Comment by jdiercks** [comment]
OK John, thanks, I'll watch for that.

**Comment by jdiercks** [comment]
Hi John, any update on this? I'm still interested in possibly submitting one or more PRs. --Jon

**Comment by Trasselfrisyr** [comment]
Fixed. Closing this thread.
